#include "skill.h"

SkillInfo skills[SKILL_COUNT] = {
    {S_EMBER, "Ember", 20, 5, T_FIRE},
    {S_VINEWHIP, "Vine Whip", 20, 5, T_GRASS},
    {S_WATERGUN, "Water Gun", 20, 5, T_WATER},
    {S_HEADBUTT, "Headbutt", 30, 7, T_NORMAL},
    {S_SLASH, "Slash", 35, 8, T_NORMAL},
    {S_FLAMEWHEEL, "Flame Wheel", 30, 10, T_FIRE},
    {S_MAGICALLEAF, "Magical Leaf", 30, 10, T_GRASS},
    {S_WATERPULSE, "Water Pulse", 30, 10, T_WATER},
    {S_RECOVER, "Recover", 20, 25, T_HEAL},
    {S_FLAMETHROWER, "FlameThrower", 35, 15, T_FIRE},
    {S_LEAFBLADE, "Leaf Blade", 35, 15, T_GRASS},
    {S_SURF, "Surf", 35, 15, T_WATER},
    {S_MEGAPUNCH, "Mega Punch", 40, 15, T_NORMAL},
    {S_FIREBLAST, "Fire Blast", 40, 20, T_FIRE},
    {S_SOLARBEAM, "Solar Beam", 40, 20, T_GRASS},
    {S_HYDROPUMP, "Hydro Pump", 40, 20, T_WATER},
    {S_MEGAKICK, "Mega Kick", 45, 20, T_NORMAL},
    {S_BLASTBURN, "Blast Burn", 45, 25, T_FIRE},
    {S_FRENZYPLANT, "Frenzy Plant", 45, 25, T_GRASS},
    {S_HYDROCANNON, "Hydro Cannon", 45, 25, T_WATER},
    {S_HYPERBEAM, "Hyper Beam", 50, 25, T_NORMAL},
    {ES_TACKLE, "Tackle", 10, 0, T_NORMAL},
    {ES_ACID, "Acid", 15, 0, T_NORMAL},
    {ES_SLUDGEBOMB, "Sludge Bomb", 20, 0, T_NORMAL},
    {ES_GUNKSHOT, "Gunk Shot", 25, 0, T_NORMAL},
    {ES_SCRATCH, "Scratch", 10, 0, T_NORMAL},
    {ES_THRUST, "Thrust", 15, 0, T_NORMAL},
    {ES_POTION, "Potion", 5, 0, T_HEAL},
    {ES_GOBLINPUNCH, "Goblin Punch", 25, 0, T_NORMAL},
    {ES_BITE, "Bite", 15, 0, T_NORMAL},
    {ES_FLAMEBURST, "Flame Burst", 20, 0, T_NORMAL},
    {ES_FIREFANG, "Fire Fang", 25, 0, T_NORMAL},
    {ES_SCORCH, "Scorch", 30, 0, T_NORMAL},
    {ES_BUBBLE, "Bubble", 20, 0, T_NORMAL},
    {ES_BUBBLEBEAM, "Bubblebeam", 30, 0, T_NORMAL},
    {ES_NATUREGRASP, "Nature's Grasp", 15, 0, T_NORMAL},
    {ES_LEECHSEED, "Leech Seed", 20, 0, T_NORMAL},
    {ES_INGRAIN, "Ingrain", 10, 0, T_HEAL},
    {ES_OVERGROWTH, "Overgrowth", 30, 0, T_NORMAL},
    {ES_CRUNCH, "Crunch", 25, 0, T_NORMAL},
    {ES_MOWDOWN, "Mow Down", 30, 0, T_NORMAL},
    {ES_MAELSTROM, "Maelstrom", 40, 0, T_NORMAL},
    {ES_METEOR, "Meteor", 50, 0, T_NORMAL},
    {ES_BULLETSEED, "Bullet Seed", 20, 0, T_NORMAL},
    {ES_SEEDBOMB, "Seed Bomb", 30, 0, T_NORMAL},
    {ES_ENERGYBALL, "Energy Ball", 35, 0, T_NORMAL},
    {ES_NATUREWRATH, "Nature's Wrath", 45, 0, T_NORMAL},
    {ES_TENTACLEPOUND, "Tentacle Pound", 30, 0, T_NORMAL},
    {ES_WRAP, "Wrap", 35, 0, T_NORMAL},
    {ES_TSUNAMI, "Tsunami", 45, 0, T_NORMAL},
    {ES_TRIATTACK, "Tri Attack", 35, 0, T_NORMAL},
    {ES_HELLFLAME, "Hellflame", 45, 0, T_NORMAL},
    {ES_SUPERNOVA, "Supernova", 70, 0, T_NORMAL},
    {S_NORMALATTACK, "Normal Attack", 10, 0, T_NORMAL}};